<?php
declare(strict_types=1);

// Bonequest SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

BonequestUtility::setRegistrar(function (BonequestUtility $u): void {
    $u->clean = [BonequestClean::class, 'call'];
    $u->done = [BonequestDone::class, 'call'];
    $u->make_error = [BonequestMakeError::class, 'call'];
    $u->feature_add = [BonequestFeatureAdd::class, 'call'];
    $u->feature_hook = [BonequestFeatureHook::class, 'call'];
    $u->feature_init = [BonequestFeatureInit::class, 'call'];
    $u->fetcher = [BonequestFetcher::class, 'call'];
    $u->make_fetch_def = [BonequestMakeFetchDef::class, 'call'];
    $u->make_context = [BonequestMakeContext::class, 'call'];
    $u->make_options = [BonequestMakeOptions::class, 'call'];
    $u->make_request = [BonequestMakeRequest::class, 'call'];
    $u->make_response = [BonequestMakeResponse::class, 'call'];
    $u->make_result = [BonequestMakeResult::class, 'call'];
    $u->make_point = [BonequestMakePoint::class, 'call'];
    $u->make_spec = [BonequestMakeSpec::class, 'call'];
    $u->make_url = [BonequestMakeUrl::class, 'call'];
    $u->param = [BonequestParam::class, 'call'];
    $u->prepare_auth = [BonequestPrepareAuth::class, 'call'];
    $u->prepare_body = [BonequestPrepareBody::class, 'call'];
    $u->prepare_headers = [BonequestPrepareHeaders::class, 'call'];
    $u->prepare_method = [BonequestPrepareMethod::class, 'call'];
    $u->prepare_params = [BonequestPrepareParams::class, 'call'];
    $u->prepare_path = [BonequestPreparePath::class, 'call'];
    $u->prepare_query = [BonequestPrepareQuery::class, 'call'];
    $u->graphql_body = [BonequestGraphql::class, 'body'];
    $u->graphql_errors = [BonequestGraphql::class, 'errors'];
    $u->result_basic = [BonequestResultBasic::class, 'call'];
    $u->result_body = [BonequestResultBody::class, 'call'];
    $u->result_headers = [BonequestResultHeaders::class, 'call'];
    $u->transform_request = [BonequestTransformRequest::class, 'call'];
    $u->transform_response = [BonequestTransformResponse::class, 'call'];
});
